name: Automated Testing

on: [push]

jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      # use cached node_modules if available
      - name: Getting Cached Modules
        uses: actions/cache@v3
        id: cache-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ github.ref_name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-${{ github.ref_name }}-
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      # install if necessary
      - name: Installing Modules
        if: steps.cache-modules.outputs.cache-hit != 'true'
        run: npm ci

      - name: Run Tests
        run: npm run test
